import Head from "next/head";
import Image from "next/image";

import Form1 from "../components/Form1";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <br />
        <h1 className="text-center">Add Insurance</h1>
        <Form1 />
      </main>
    </>
  );
}
